### ISSUE TITLE
Cannot compile proceedings

### ISSUE THREAD

**Issue by tnaumann** [rycolab/aclpub2#101]
We need additional information on how to fix a paper that cannot be compiled. Specifically, we are getting an error suggesting that we open the PDF and export it again, but trying this across 4 different PDF programs fails to solve the problem. Neither we nor the authors know how to fix the problem so that their paper can be included in the proceedings. Please let us know how to proceed.

Error message:
```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/tjn/tmp/aclpub2/aclpub2/generate.py", line 399, in create_watermarked_pdf
    raise Exception(
Exception: Sorry but it seems I cannot compile paper 6.pdf and it will not be added to the output folder!
It is generally due to a PDF with a problematic internal links.
A "possible" solution is to open the PDF with any preview system and export it again.
"""

The above exception was the direct cause of the following exception:

Exception: Sorry but it seems I cannot compile paper 6.pdf and it will not be added to the output folder!
It is generally due to a PDF with a problematic internal links.
A "possible" solution is to open the PDF with any preview system and export it again.
None

Sorry. I have problems compiling the watermarked papers. Press Enter to process another paper or Ctrl+C to quit.
```

**Comment by crux82** [comment]
Hi Tristan

can you share with me or @ryancotterell (the publication chairs of NAACL) the problematic PDF in a private message?
So we can understand what is happening and solve this issue or provide a better message. 

Danilo

**Comment by crux82** [comment]
I used the function "Export as PDF" from the Preview of my MAC to re-export the problematic PDF. 
I then removed the pax file associated with it and recompiled it. 
@tnaumann if it works, please close this issue.

**Comment by tnaumann** [comment]
Confirming that deleting all `.pax` files prior to calling `./bin/generate` fixes the problem, regardless of re-exporting the PDF. I'll close the bug as it's no longer blocking proceedings generation.

It's unclear to me why the `.pax` that was generated by `openreview/or2papers.py` consistently produces an error, but allowing `./bin/generate` to create these files proceeds without error. Given that this is the case, should we disable the creation of `.pax` files in `openreview/or2papers.py`?

**Comment by tnaumann** [comment]
Sorry! Realizing now that `openreview/or2papers.py` does _not_ create these files; instead, they were left over in the source directory after running `./bin/generate`. Since that's the case, please ignore my last note about disabling their creation in `openreview/or2papers.py`.

**Comment by tnaumann** [comment]
Following up, part of my confusion here was that `.pax` files are _output_ to the `papers` _input_ directory. I did not notice this and so even though I had tried "Export as PDF", I had _not_ removed the pax file that was associated with it. Both are required to successfully compile. 

A potential mitigation to avoid confusion in future would be to output the `.pax` files to either the `build` or `output` directories (alongside other outputs) so that `./bin/generate ${INPUT} --proceedings --overwrite` does not try to use stale `.pax` files.

**Comment by MirunaClinciu** [comment]
I encountered this issue as well. I exported the files as PDFs and corrected them, thinking they might be corrupted, but unfortunately, that didn't resolve the problem. I also removed the PAX files and regenerated the proceedings, but still no luck. I'm not sure how to fix this yet. 

I just started running `./bin/generate examples/acl_2024_proceedings/findings --proceedings --handbook --overwrite --nopax` and I'm hopeful this will work. If not, I'll update here. I hadn't even realized there was an issue because I didn't notice that the watermarks weren't created. With so many papers to handle, it's difficult to check everything, especially when it takes two hours to get the output.

**Comment by crux82** [comment]
@MirunaClinciu  In ``./bin/generate examples/acl_2024_proceedings/findings --proceedings --handbook --overwrite --nopax`` I would suggest to remove ``--handbook`` as you are not compiling the handbook. 

Did you try to temporarily remove the specific paper from the papers.yml file? It could be useful to understand if this is the problem.

**Comment by MirunaClinciu** [comment]
Hi @crux82,

I haven’t tried removing the papers from the paper folder or the yaml file yet. I’m experiencing this issue with just three papers out of the entire set.

Here’s what I’ve tried so far:
1. Running `./bin/generate examples/acl_2024_proceedings/findings --proceedings --overwrite`.
2. Running `./bin/generate examples/acl_2024_proceedings/findings --proceedings --overwrite --nopax`.
3. Running `./bin/generate examples/acl_2024_proceedings/findings --proceedings --overwrite` and manually removing the PAX files from the papers folder.
4. Converting and exporting the PDFs using Adobe Acrobat, and even attempting to correct them.

Unfortunately, none of these attempts have resolved the issue.

**Comment by crux82** [comment]
@MirunaClinciu I sent you a private mail to have details about these problematic PDFs.

**Comment by ryancotterell** [comment]
If you email me the papers as well, I can take a look. It's often a formatting error.

**Comment by juliawatson** [comment]
Hello,

I'm preparing the proceedings for CoNLL 2024, and I'm encountering this error for one of the pdfs.

The error looks like:

```
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/julia/Documents/Fall2024/CoNLL 2024/aclpub2/aclpub2/generate.py", line 450, in create_watermarked_pdf
    raise Exception(
Exception: Sorry but it seems I cannot compile paper 27.pdf and it will not be added to the output folder!
It is generally due to a PDF with a problematic internal links.
A "possible" solution is to open the PDF with any preview system and export it again.
"""

The above exception was the direct cause of the following exception:

Exception: Sorry but it seems I cannot compile paper 27.pdf and it will not be added to the output folder!
It is generally due to a PDF with a problematic internal links.
A "possible" solution is to open the PDF with any preview system and export it again.
Compiling 70
None

Sorry. I have problems compiling the watermarked papers. Press Enter to process another paper or Ctrl+C to quit.
```

I have tried:
• Exporting from pdf using preview on mac
• Deleting pax files manually and re-running
• Running with the --nopax flag

I'm pretty sure this pdf is the issue, since the proceedings compile when I temporarily remove the paper from the papers.yml file.

Would someone be able to take a look at the pdf and see if there's a formatting error?

**Comment by crux82** [comment]
@juliawatson as I am one of the EMNLP publication chairs can you send me the file privately? Without the PDF, it isn't easy to help.

**Comment by juliawatson** [comment]
@crux82 Thanks for your quick reply. I was able to resolve the issue by emailing with the authors about possible formatting issues.

For people that encounter this issue in the future -- in our case it had to do with the way the author names were formatted on the first page. It was tricky to catch because the paper passed aclpubcheck.

**Comment by j0ma** [comment]
I'm one of the Publication Chairs for the Multilingual Representation Learning Workshop at EMNLP this year. I'm also facing this same issue with one of our PDFs. I've tried (a) manually deleting the .pax files and rerunning, (b) running with --nopax and (c) exporting via Preview, all without success. I can tell that similar to @juliawatson 's case it must be something with the first page of the paper since the proceedings compile if I leave out the first page of the problematic PDF. 

Is there a way to fix it without access to the original LaTeX source?

**Comment by crux82** [comment]
@j0ma try to export the paper by... "printing" in preview. 
You start printing (being sure that the proportion is 100%). Then you should be able to select "Open In Preview" and save this "printed" copy. It should work. Otherwise, send it to me privately, and I should be able to convert it.
