### ISSUE TITLE
Faulty PDF outline

### ISSUE THREAD

**Issue by texttheater** [rycolab/aclpub2#138]
In the SIGDIAL example, the generated `proceedings.pdf` has an outline (can be displayed in a side pane in a suitable PDF viewer such as Evince) which consists of entries that all read TEMPLATETITLE and link to page i. They should link to the papers and be titled accordingly.

**Comment by nilinykh** [comment]
This is still an issue. Currently compiling proceedings for the workshop and a side pane with the content of the generated proceedings pdf still has TEMPLATETITLE in it, nothing else.

**Comment by nilinykh** [comment]
@texttheater Did you manage to solve the problem?

**Comment by crux82** [comment]
I think that it is due to this line:

https://github.com/rycolab/aclpub2/blob/6151c78cd65b8df14953dcc18c9d6cb44a2b3db3/aclpub2/templates/proceedings.tex#L413

I suppose that, if you comment/remove this line, the bookmarks should disappear. 
But I am not sure if this introduces other issues...

@zhzhang do you remember why we added the above line?

**Comment by texttheater** [comment]
@nilinykh Thanks! I already fixed the issue via another route, but learning about `\phantomsection` enabled me to tackle #152.
