### ISSUE TITLE
infinite copy loop if calling aclpub2 on the working directory

### ISSUE THREAD

**Issue by patrick-s-h-lewis** [rycolab/aclpub2#72]
The way my directory was structured, acl-pub2 was a submodule, and I was calling the generate command on my working directory.

thus Line 129 got into a problematic loop:
`shutil.copytree(input_path, Path(output_dir, "inputs"))`
(https://github.com/rycolab/aclpub2/blob/main/aclpub2/generate.py#L129)
trying to copy a path that contains the output_dir into the output_dir.

Basically, the current code breaks when the input path is the same path as the working directory.
i.e. 
`aclpub2/bin/generate ./ --proceedings —overwrite`
breaks
But 
```
cd ..
aclpub2/bin/generate ./SPA-NLP/. --proceedings --overwrite
```
Is ok.

Please fix or make it clear that you cannot call generate on the working directory.

**Comment by esalesky** [comment]
Seconding this issue; I previously ran `aclpub2/bin/generate ./ --proceedings —overwrite` successfully with `aclpub2` as a submodule as set up for us, but after updating aclpub2 this creates a breaking loop of 
`[Errno 63] File name too long: 'output/inputs/output/inputs/output/inputs/output/inputs/output/inputs/output/inputs/output/inputs/output/inputs/output/inputs/output/input` ... 
I tried running from the directory back as suggested above but got the same error.

**Comment by crux82** [comment]
Unfortunately, this bug is still not fixed (we are working on that).

It is essentially due to the fact that the software tries to (recursively!!!) copy the folder containing the input material (i.e., the yaml files, the pdf papers, and attachments) in the output directory.

A good "workaround" is to pack all the input material in an internal folder (e.g., `input`) that is inside your main folder and launch 

`aclpub2/bin/generate ./input --proceedings --overwrite`

at the end, your main folder should contain an additional folder named `output` containing the proceedings and a copy of the initial `input` folder.

**Comment by esalesky** [comment]
Thanks! I've updated to do this

**Comment by crux82** [comment]
The last commit [d09be5e](https://github.com/rycolab/aclpub2/commit/d09be5e1b564e5ce1ed6d6427330301efe75ce06) should solve the issue. 

@esalesky @patrick-s-h-lewis can you please check if it works now? Thanks!
